Repository cloudnative-pg/charts, pull requests merged in 2025-04, with the labels that each got.

#320 CI: Add codespell check
  .github/workflows/lint.yml
  CODE-OF-CONDUCT.md
  charts/cloudnative-pg/README.md
  charts/cloudnative-pg/values.yaml
  charts/cluster/docs/Getting Started.md
  charts/cluster/templates/_helpers.tpl
Labels: size:S, lgtm

#372 feat(cnpg): Adding `topologySpreadConstraints` support to the deployment
  charts/cloudnative-pg/README.md
  charts/cloudnative-pg/templates/deployment.yaml
  charts/cloudnative-pg/values.schema.json
  charts/cloudnative-pg/values.yaml
Labels: chart( operator ), size:S, lgtm

#550 fix(cluster): allow using storage container default for wal and data backup encryption by setting an empty value
  charts/cluster/templates/_backup.tpl
Labels: size:XS, lgtm
